### PR TITLE
fix staging site crash because of tmp dir in mu-plugs

### PR DESCRIPTION
**Pull request by backamblock**

### CODE REVIEW

**Comment by backamblock** [comment]
damn you are too fast :D just made a screenshot but didn't get to upload it🥇

**Comment by jessuppi** [comment]
Btw, I think there is a bug in `ss-install-wordpress-mu-plugins` when using custom plugins in `ss-config` that is causing that `tmp` folder to appear sometimes in the /mu-plugins/ folder, I haven't got around to checking it.

**Comment by backamblock** [comment]
hm maybe because you use regular rm without -r which will not delete directories

image

the -i is just for testing
i usually use rm -rf, but force might lead to data loss depending on where it is used

image

**Comment by jessuppi** [comment]
`rm` is actually defined in ss-functions to behave like `rm -rf`

I've been in the process of converting these all to `ss_rm` instead after a guy on StackOverflow told me it was better practice.

**Comment by backamblock** [comment]
Pull request updated to use ss_rm 👍🏻 

image

**Pull request merged**
