### PR TITLE
SS_DASHBOARD fix, rclone working, small fixes/changes - please check

### PR DESCRIPTION
**Pull request by backamblock**

### CODE REVIEW

**Comment by backamblock** [comment]
@jessuppi what do you think about this?

**Comment by backamblock** [comment]
@jessuppi rclone works fine now, got rate limited a few times on b2. Lucky me used a free b2 account for testing, would've paid some $$$ for API requests if i wasn't limited to free...

@everybody
Words of warning: when uploading to b2, do NOT use /var/www/ it will most likely kill your free daily transactions in one run. i got to over 3500 while testing before they could deactivate my api because of 1k transfers 🥇 

for parallel transfers. 1000 pins my 2c amd epyc vps to 100% CPU, so i'd recommend staying under 500 parallel transfers if you want to sync /var/www/ as a whole. take 40% of these values for 1c vps, not more
for /var/www/backups you can keep the default value of 15

i would definitely recommend using ss-dump-files for a time-correct backup as many things can change in the 10+ minutes rclone will run. but it will use more space of course. i will use it because it is easier to keep track of versions of 2-5 vs 2k files when it comes to restoring them. also i don't want to pay for api transactions on b2. decide for yourself.

**Comment by backamblock** [comment]
@jessuppi Hey, please check the commits when you are free. i'd like to close this so i can try some things without spamming this with commits 👍🏻

**Comment by jessuppi** [comment]
@backamblock Thanks for all your research and help on this, however I'm not very good at Git and there are 28 commits in this single Pull Request which makes it nearly impossible for me to review properly. If possible, it would really help my ability to accept (certain) commits if they were divided into smaller changes?

**Comment by backamblock** [comment]
@jessuppi yes that is exactly my problem. it seems that i can only make one pull request and whatever i commit to my fork after this, is automatically added :/ i can just close/cancel the pull request

**Comment by jessuppi** [comment]
Much appreciated, I will cancel this PR for now since it's too difficult to review entirely.

**Comment by backamblock** [comment]
i don't understand, what should i do now? i can not take my commits away from my master branch?

**Pull request closed without merging**
